name: release
on:
  # push:
  workflow_dispatch:

jobs:
  release-worker:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      ssh_key: ${{ secrets.SSH_PRIVATE_KEY_FOR_SYNC }}
      git_user: l
      git_email: l@x-cmd.com
      CONCURRENCY: 10
    steps:
      - name: main
        uses: x-cmd/action@main
        with:
          code: x ws fabu-release
